//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Codigo_Venta { get; set; }
        public int Codigo_Producto { get; set; }
        public int Codigo_Cliente { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
